# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nickjones-vestal_versions}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["laserlemon", "nickjones"]
  s.date = %q{2011-07-01}
  s.description = %q{Keep a DRY history of your ActiveRecord models' changes}
  s.email = ["steve@laserlemon.com", "darellik@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "generators/vestal_versions/templates/initializer.rb",
    "generators/vestal_versions/templates/migration.rb",
    "generators/vestal_versions/vestal_versions_generator.rb",
    "init.rb",
    "lib/vestal_versions.rb",
    "lib/vestal_versions/changes.rb",
    "lib/vestal_versions/conditions.rb",
    "lib/vestal_versions/configuration.rb",
    "lib/vestal_versions/control.rb",
    "lib/vestal_versions/creation.rb",
    "lib/vestal_versions/options.rb",
    "lib/vestal_versions/reload.rb",
    "lib/vestal_versions/reset.rb",
    "lib/vestal_versions/reversion.rb",
    "lib/vestal_versions/users.rb",
    "lib/vestal_versions/version.rb",
    "lib/vestal_versions/version_tagging.rb",
    "lib/vestal_versions/versioned.rb",
    "lib/vestal_versions/versions.rb",
    "nickjones-vestal_versions.gemspec",
    "test/changes_test.rb",
    "test/conditions_test.rb",
    "test/configuration_test.rb",
    "test/control_test.rb",
    "test/creation_test.rb",
    "test/options_test.rb",
    "test/reload_test.rb",
    "test/reset_test.rb",
    "test/reversion_test.rb",
    "test/schema.rb",
    "test/test_helper.rb",
    "test/users_test.rb",
    "test/version_tagging_test.rb",
    "test/version_test.rb",
    "test/versioned_test.rb",
    "test/versions_test.rb"
  ]
  s.homepage = %q{http://github.com/nickjones/vestal_versions}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Keep a DRY history of your ActiveRecord models' changes}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

